Repository Metropolia-ZeroUI/DoseLoop, pull requests merged in 2023-03, with the labels that each got.

#14 Ui changes, Nav component
  README.md
  app/build.gradle
  app/src/main/java/com/example/doseloop/DoseLoopApplication.kt
  app/src/main/java/com/example/doseloop/MainActivity.kt
  app/src/main/java/com/example/doseloop/fragments/DrawerExampleFragment.kt
  app/src/main/java/com/example/doseloop/fragments/HomeFragment.kt
  app/src/main/res/drawable/bottom_nav_colors.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_menu.xml
  app/src/main/res/drawable/ic_mic.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/drawer_menu.xml
  app/src/main/res/layout/fragment_drawer_example.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/menu/bottom_menu.xml
  app/src/main/res/navigation/navigation.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: good first issue

#18 fix retarded overloads
  app/src/main/java/com/example/doseloop/comms/MainTest.kt
  app/src/main/java/com/example/doseloop/comms/impl/Message.kt
  app/src/main/java/com/example/doseloop/comms/impl/PhoneNumber.kt
Labels: bug

#37 Changing medicine times: Ui for now only Ui. Functionality in progress.
  README.md
  app/src/main/java/com/example/doseloop/comms/impl/Message.kt
  app/src/main/java/com/example/doseloop/fragments/DateTimeSettingFragment.kt
  app/src/main/java/com/example/doseloop/fragments/HomeFragment.kt
  app/src/main/java/com/example/doseloop/util/Constants.kt
  app/src/main/java/com/example/doseloop/viewmodel/DateTimeSettingViewModel.kt
  app/src/main/res/drawable/bg_pill.png
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_date_time_setting.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/navigation/navigation.xml
  app/src/main/res/values/strings.xml
Labels: invalid
